### ISSUE TITLE
Changing font

### ISSUE THREAD

**Issue by xgeek-cub** [moetunes/Nextwm#12]
`FONTNAME "-*-snap-*-*-normal-*-10-*-*-*-*-*-*-*"`
what if I what to use a ttf font? does this line work with xft or any other method of declaration? How exactly?

**Comment by bbenne10** [comment]
@moetunes: Would you consider adding something like the approach taken by monsterwm? Wherein a branch is maintained that is patchable onto master? I might be able to patch in pango support (which makes some really cool things possible - like "free" colored status bars without having to maintain the bar text parsing that other solutions require)

**Comment by moetunes** [comment]
I'm happy to have a look at any code you come up with and then we can decide where to take it from there.

Cheers
