### ISSUE TITLE
create release for packaging Nextwm

### ISSUE THREAD

**Issue by diogoleal** [moetunes/Nextwm#17]
Hi Moetunes,

Create a release so that create distribution package for nextwm.  Because most do not accept softwares that dont have a version.

**Comment by moetunes** [comment]
Hi Diegoleal,

Nextwm is the development version of snapwm. The snapwm-stable repo has less updates and should be more appropriate for users with less time or technical skills.
I've made a release ffor both versions on here on github.
Hope that helps.

Cheers

**Comment by diogoleal** [comment]
Moetunes, 

I not knew snapwm. I will packaged snapwm.
I tested sanpwm and liked much and  i'm using. 

Very good job!!
